# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Install `ajv` as a dev dependency
RUN npm install --save-dev ajv

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 1337

# Start the application
CMD ["npm", "run", "develop"]
